version: '3.8'

services:
  frontend:
    build:
      context: ./message-next-web
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - ./message-next-web/.env.local
    volumes:
      - ./message-next-web:/app
      - /app/node_modules
    networks:
      - app-network

networks:
  app-network:
    driver: bridge